server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  #spring:
  redis:
    host: 114.55.9.31
    port: 6379
    database: 0
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
    password: redis123
  cloud:
    nacos:
      discovery:
        server-addr: 114.55.9.31:8848 # nacos服务地址
  #spring:
  rabbitmq:
    host: 192.168.5.102
    port: 5672
    virtual-host: /srbhost
    username: srbuser
    password: 123456

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  #feign:
  sentinel:
    enabled: true

logging:
  level:
    com.w.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口
#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: 你的keyid
    key-secret: 你的keysecret
    template-code: 你的短信模板code
    sign-name: 你的短信模板签名
#邮箱
qq:
  email:
    from_email: 973169778@qq.com
    pwd: jgdgsdqzpbmbbbgf
